frontend/src/actions/handleSick.js, frontend/src/actions/types.js, frontend/src/reducers/postReducer.js, frontend/src/routes/CriticalQuestions/index.js, frontend/src/routes/Dashboard/index.js
=> 23: Add US Embassy link

frontend/src/actions/story.js, frontend/src/css/index.css, frontend/src/reducers/story.js, frontend/src/routes/Dashboard/index.js, frontend/src/routes/Dashboard/styles.module.css
=> 50: Add conditional suggestions links in frontend

frontend/src/routes/CriticalQuestions/index.js
went missing on story merge: from PR #53
=> recover missing postalCode 

frontend/src/actions/symptoms.js, frontend/src/routes/Alert/index.js, frontend/src/routes/CriticalQuestions/index.js, frontend/src/routes/MyStory/index.js, frontend/src/routes/MyStory/styles.module.css, frontend/src/routes/Symptoms/index.js, frontend/src/text.json
=> #78: Improve flow issues

backend/auth/main.py, backend/router/stories.py, backend/stories/crud.py, frontend/src/routes/CriticalQuestions/index.js
closes #72 
The actual changes were a different way to look a `token_data` - we were only triggering updates if the token was a user's, now it's triggered even if it's a story's.
Another change was to the actual logic of the update, because the prior approach didn't update medical conditions!
=> 72: Fix auth issues on second story flow run

frontend/src/actions/story.js
=> Bug: Change citizenship for location in a link's validation

frontend/src/routes/CriticalQuestions/index.js
when user claims is not sick
closes #39
=> Do not show "When did you start feeling sick" datepicker 

frontend/src/components/Map/index.js
New api: https://freegeoip.app/
✅  supports https 🔒 
✅  _"You're allowed up to 15,000 queries per hour by default."_ 🥇 
for #91
=> Change geolocation by IP api

frontend/src/actions/resources.js, frontend/src/routes/Dashboard/index.js
=> Rename suggestions for resources

frontend/src/actions/resources.js
=> fix 'Information for US travelers' link

frontend/src/actions/story.js, frontend/src/routes/CriticalQuestions/index.js
* Fix undefined `story.travels`
* Don't break when travels response is not a `200 OK`
for #128
=> Fix 128 - undefined travels

frontend/src/components/Map/index.js
=> added non-us map layer and edited world map layer

backend/alembic/versions/2551e1a3cb06_add_spam_column_to_stories.py, backend/stories/models.py, backend/stories/schemas.py
Added spam column to stories table. Initialized with 0 by default. Every time a story is marked as spam, this value should be incremented.
=> 175:add spam field

frontend/src/components/Map/index.js
=> Revert "Bug/243 water markers"

backend/NytLiveCounty/crud.py, backend/app.py, backend/tests/test_nyt_county.py, frontend/src/routes/Consent/index.js, frontend/yarn-error.log
=> Revert "Fix database timeout issue during NYT data population"

frontend/src/routes/Home/index.js, frontend/src/routes/Home/styles.module.css
=> update home page

frontend/src/components/Map/index.js, frontend/src/components/SimpleMap/index.js
=> add scroll

backend/router/stories.py, backend/stories/crud.py, backend/stories/models.py, backend/stories/schemas.py
=> backend for explore and search

backend/requirements.txt
downgrade pyjwt, ci should pass now.
=> downgrade pyjwt to 1.7.1

.pre-commit-config.yaml, frontend/src/components/Widget/index.js, frontend/src/components/Widget/styles.module.css, frontend/src/routes/Dashboard/index.js
I have moved the status bar to the widget.
I have also made a small change to the pre-commit config file,
changing the prettier repo to the new one (as suggested by the error message the
pre-commit gave me as it failed my commit)
=> moving the status bar to the widget
